### ISSUE TITLE
嵌套无法校验

### ISSUE THREAD

**Issue by scyslz** [liangbaika/validate#3]
对象嵌套无法校验

**Comment by liangbaika** [comment]
我这边没有复现  ,   给出复现步骤   截图 说明

**Comment by liangbaika** [comment]
@gitHubForLz

**Comment by scyslz** [comment]
> 我这边没有复现 , 给出复现步骤 截图 说明

@Data
public class TransferOrderReq {
     @AbcValidate(fun = Check.NotEmpty,message = "不能为空" ,required = true )
    private List<TransferOrderDetailReq> orderDetail;
}

@Validated
@Data
public class TransferOrderDetailReq {
    @AbcValidate(fun = Check.Null, message = "库存id不能为空弄",required = true)
    private Long warehouseStockId;
}
你看我这校验对不对 warehouseStockId!=null

**Comment by liangbaika** [comment]
@AbcValidate(fun = Check.Null, message = "库存id不能为空弄",required = true)  这个是校验空的 非空用 NotNull  

对象嵌套无法校验 什么意思呢 @gitHubForLz

**Comment by scyslz** [comment]
> @AbcValidate(fun = Check.Null, message = "库存id不能为空弄",required = true) 这个是校验空的 非空用 NotNull
> 
> 对象嵌套无法校验 什么意思呢 @gitHubForLz

校验这个对象，list不为空，校验list中对象的某个字段不能为空
![image](https://user-images.githubusercontent.com/39955047/99352420-935a8a80-28dd-11eb-9567-70c53b469f8b.png)
 不好意思，自己写错了

在List加上@Valid就可以检验里面的对象了
