### ISSUE TITLE
感觉还是需要再加强一点

### ISSUE THREAD

**Issue by chenrenfei** [liangbaika/validate#4]
1、注解是否应该增加几个常用的@NotEmpty 直接使用，简化注解
2、建议再提供一个内部方法中快捷验证工具方法，比如：
ValidateBuilder.notNull("姓名\性别不能为空",staffName,sexType).mail(email).idCard(idCard).validate();

或者这样:

ValidateBuilder.vali(mail(vo.email).messge("邮箱地址不合法")).vali(notEmpty(vo.name,vo.id)).do();

既可以注解也可以用工具方法灵活实现，给开发者更多不同场景的灵活配合，当然还有集合验证。

**Comment by liangbaika** [comment]
第一点  这个框架完全兼容标准的jsr303验证的 你可以直接使用 javax.validate包下的注解 比如     @NotBlank
 等等
第二点  估计会用工具方法实现 属于增强功能 放后边 当然你也可以提pr  @chenrenfei

**Comment by liangbaika** [comment]
已经发版了哈  ValidateBuilder @chenrenfei

**Comment by liangbaika** [comment]
请使用 1.2.0版本
