### ISSUE TITLE
Validation.buildDefaultValidatorFactory().getValidator().validate(xxxxx)这种手动校验貌似无效

### ISSUE THREAD

**Issue by fendo8888** [liangbaika/validate#5]
Validation.buildDefaultValidatorFactory().getValidator().validate(xxxxx)这种手动校验貌似无效，不会进入CheckUtil类中的方法

**Comment by liangbaika** [comment]
调错api了

**Comment by liangbaika** [comment]
> 调错api了

请参考readme里的普通代码调用方式
